CREATE TABLE public.contact (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    email varchar(100) NOT NULL UNIQUE,
    phone_number varchar(12) NOT NULL UNIQUE,
    created_at timestamp NOT NULL
);

ALTER TABLE IF EXISTS public.contacts OWNER to postgres;